name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    name: Build Linux x86_64
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libncurses5-dev
          
      - name: Build
        working-directory: v4
        run: make
        
      - name: Prepare artifact
        run: |
          mkdir -p dist
          cp v4/vmanager dist/vmanager-linux-amd64
          chmod +x dist/vmanager-linux-amd64
          cd dist
          sha256sum vmanager-linux-amd64 > vmanager-linux-amd64.sha256
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-amd64
          path: dist/*

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: brew install curl ncurses
        
      - name: Build
        working-directory: v4
        run: make
        
      - name: Prepare artifact
        run: |
          mkdir -p dist
          cp v4/vmanager dist/vmanager-macos-amd64
          chmod +x dist/vmanager-macos-amd64
          cd dist
          shasum -a 256 vmanager-macos-amd64 > vmanager-macos-amd64.sha256
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-amd64
          path: dist/*

  release:
    name: Create Release
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Prepare release
        run: |
          mkdir -p release
          cp artifacts/linux-amd64/* release/
          cp artifacts/macos-amd64/* release/
          cd release
          cat *.sha256 > SHA256SUMS
          ls -lh
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
          body: |
            # vmanager v4.0.0
            
            Proxmox VM Management Tool
            
            ## Features
            
            - CLI and TUI dual modes
            - Batch operations (ranges, comma-separated)
            - Complete VM management
            - Real-time monitoring
            - Modular architecture
            - Zero compiler warnings
            
            ## Supported Platforms
            
            - Linux x86_64
            - macOS x86_64
            
            ## Installation
            
            ```bash
            # Download binary
            wget https://github.com/sscaifesu/vmanager/releases/download/v4.0.0/vmanager-linux-amd64
            
            # Verify checksum
            sha256sum -c SHA256SUMS
            
            # Install
            chmod +x vmanager-linux-amd64
            sudo mv vmanager-linux-amd64 /usr/local/bin/vmanager
            
            # Use
            vmanager --help
            vmanager --tui
            ```
            
            ## Team
            
            Copyright (C) 2025 YXWA Infosec Lab  
            Authors: Crystal & evalEvil  
            License: GPL-3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
